[package]
name = "tokio-example"
version = "0.1.0"
authors = ["sabinote <github@sabinote.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.0", features = ["full"] }
reqwest = "*"